version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install

  pre_build:
    commands:
      - echo ENV = $ENV

      - if [ "$ENV" = "dev" ]; then
          source env/dev.env;
        else
          source env/qa.env;
        fi

      - echo Bucket = $S3_BUCKET
      - echo CloudFront = $CLOUDFRONT_ID

  build:
    commands:
      - echo Building React app
      - npm run build

  post_build:
    commands:
      - echo Uploading build to S3
      - aws s3 sync build/ s3://$S3_BUCKET --delete

      - echo Invalidating CloudFront cache
      - aws cloudfront create-invalidation \
        --distribution-id $CLOUDFRONT_ID \
        --paths "/*"

artifacts:
  files:
    - '**/*'