version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install

  pre_build:
    commands:
      - echo Selected ENV = $ENV

      # Load environment file
      - if [ "$ENV" = "dev" ]; then
          echo Loading DEV config;
          source ./env/dev.env;
        else
          echo Loading QA config;
          source ./env/qa.env;
        fi

      # Debug (this is the important fix part)
      - echo Bucket name is: $S3_BUCKET
      - aws s3 ls

  build:
    commands:
      - echo Building React app
      - npm run build

  post_build:
    commands:
      - echo Uploading build to S3
      - aws s3 sync build/ s3://$S3_BUCKET --delete --region us-east-1

      - echo Invalidating CloudFront cache
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'