version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    commands:
      - echo Moving to frontend folder
      - cd frontend
      - npm install

  pre_build:
    commands:
      - echo ENV = $ENV
      - if [ "$ENV" = "dev" ]; then source ../env/dev.env; else source ../env/qa.env; fi
      - echo Bucket = $S3_BUCKET

  build:
    commands:
      - echo Building React app
      - npm run build

  post_build:
    commands:
      - echo Uploading build to S3
      - aws s3 sync build/ s3://$S3_BUCKET --delete --region us-east-1

      - echo Invalidating CloudFront
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'